name: KeyShift
options:
  bundleIdPrefix: com.keyshift
  deploymentTarget:
    macOS: "12.0"
  createIntermediateGroups: true
  groupSortPosition: top
  generateEmptyDirectories: true

packages:
  Yams:
    url: https://github.com/jpsim/Yams.git
    from: "5.0.0"
  LaunchAgent:
    url: https://github.com/emorydunn/LaunchAgent.git
    from: "0.1.0"

targets:
  KeyShift:
    type: application
    platform: macOS
    deploymentTarget: "12.0"
    sources:
      - path: Sources/KeyShift
        type: group
      - path: Sources/KeyShiftApp
        type: group
        excludes:
          - "**/*.entitlements"
    resources:
      - Sources/KeyShiftApp/Resources
    dependencies:
      - package: Yams
      - package: LaunchAgent
    entitlements:
      path: KeyShift.entitlements
    settings:
      base:
        PRODUCT_NAME: KeyShift
        PRODUCT_BUNDLE_IDENTIFIER: com.keyshift.app
        INFOPLIST_KEY_LSUIElement: true
        INFOPLIST_KEY_NSHumanReadableCopyright: "© 2024 KeyShift"
        INFOPLIST_KEY_CFBundleDisplayName: KeyShift
        MARKETING_VERSION: "1.0.0"
        CURRENT_PROJECT_VERSION: "1"
        SWIFT_VERSION: "5.0"
        MACOSX_DEPLOYMENT_TARGET: "12.0"
        CODE_SIGN_STYLE: Automatic
        DEVELOPMENT_TEAM: "2D4G3J6Y8W"
        CODE_SIGN_ALLOW_ENTITLEMENTS_MODIFICATION: true
        ENABLE_HARDENED_RUNTIME: true
        GENERATE_INFOPLIST_FILE: true
        COMBINE_HIDPI_IMAGES: true

schemes:
  KeyShift:
    build:
      targets:
        KeyShift: all
    run:
      config: Debug
    archive:
      config: Release